### ISSUE TITLE
No device manager for network connections

### ISSUE THREAD

**Issue by Greystone4** [kg4vdk/arcos-linux-modules#21]
Hi, I successfully created a bootable USB, booted twice and everything seems functional except for network connections.  I try to left click on the network connections in the lower left of the screen and do not see options for available networks like I see in Windows and Android.  

If I go to the Administration menu for Device Manager, no Device Manager utility is found.  I am also not able to find Device Manager using the search function.

I'm using an older Dell laptop with an i3-4010u CPU.   This laptop is probably 10-12 years old.

I'm new to Linux and am mostly a windows user. - thanks

**Comment by kg4vdk** [comment]
It sounds like your machine likely has a WiFi chipset which is not supported in the Linux kernel. To investigate this further, detailed system information is required.

Please use the "System Info" utility and select the "Copy to clipboard" option to create a text file with the report information. Include the system information report as an attachment.

**Comment by Greystone4** [comment]
System info attached - thx
[system info.txt](https://github.com/user-attachments/files/16642921/system.info.txt)

**Comment by kg4vdk** [comment]
Another user had success installing the proprietary driver using these steps:

```
sudo apt install firmware-b43-installer
sudo modprobe -r b43
sudo modprobe -r ssb
sudo modprobe b43
```
https://forums.linuxmint.com/viewtopic.php?p=1855702#p1855702

Let me know if this helps make progress, and I can help you make the changes persistent by putting the necessaries in a USER module.

**Comment by Greystone4** [comment]
Thanks - should I have an ethernet connection when I run the first command?  When I run it in a disconnected state, I get a couple errors about not being able to resolve some URL's.

I ran all four commands and it didn't seem to have any impact.
Thanks again

**Comment by Greystone4** [comment]
Results of running first command attached

[first command.txt](https://github.com/user-attachments/files/16643254/first.command.txt)

**Comment by kg4vdk** [comment]
Yes, you will need to have an internet connection before running the `apt install` command.
