### ISSUE TITLE
No persistent storage when booting from SD card

### ISSUE THREAD

**Issue by ag5ym** [kg4vdk/arcos-linux-modules#44]
I have tried creating the on different computers, different USB and SD cards, different OS’s, and different image writing software. Am I just missing something? Should the image take the full device? 
I am away from my QTH at this time so I am unable to create media with an older version for testing, but that only other thing i can think about doing at this point. 

Any suggestions would be appreciated. 

I have enjoyed playing with this project of yours an have been trying to get a setup ready to show to my club. Keep up the good work. 

Thanks in advance 

Travis
AG5YM
73

**Comment by kg4vdk** [comment]
Hey Travis,

I'm sorry to hear you're having some difficulties, and I appreciate your tenacity! If I understand correctly, you're able to write the ISO to your USB and boot from it. However, you're not seeing any persistent storage (and possibly receiving an error notification when arcOS starts regarding this). 

If that is correct, can you please walk me through the steps you take to get to that point? Which OS/image writing tool do you use? You mention using different OS's and tools, but let's start by working with what you _prefer_ to use. 

I know of one specific situation that similarly affected another user, and it involved the use of Rufus as the image writing tool. 

![Screenshot_20241125-182153.png](https://github.com/user-attachments/assets/5303c8ad-1256-4065-8d1c-c727ca74897d)

We'll get you sorted out, and maybe this can help inform some changes/additions to the documentation page. 

Mike

**Comment by ag5ym** [comment]
VHello Mike,

 

So here is the steps I am using:

1.	Downloaded the new Hotel ISO on my Windows 11 laptop.
2.	Used BalenaEtcher to create the USB stick. I have tried multiple
devices. With today's attempt I used a brand new PNY 32 gb USB 2.0. The
write and verify worked correctly.
3.	Inserted the drive into a Toshiba Satellite E45W laptop configured
to boot from USB first and the internal HDD. It did this as expected. But I
get the following message:

 



 

So I then tried creating another flash drive using the Raspberry PI Imaging
tool. It had the same results. 

I then tried creating a drive using the Foxtrot release and it does the same
thing. I know that it worked the past when created on my main laptop that I
am now using for this testing. I really thing I am doing something wrong
but not sure how. 

 

I was able to download and create a new flash drive with the current version
of Ubuntu on it. I installed it on Dell Venue 11 Pro 7140. I then walked
thru the step that I did above using Raspberry Pi Imager. I got the same
results and error. 

 

I will be honest with and let you know I am doing this in a hospital room
while I set with my wife so I am working on not enough sleep most of the
time. Having said that I still do not understand why I am having so much
trouble.

Please let me know if there are any logs I can look at or if you have any
questions or feedback. 

 

Again Thank you. I am just trying to keep myself busy and I have a computer,
a radio, and a Digrig so I thought this might be a good time to work out
some of the details and configurations.

 

Travis Logan

AG5YM

73

**Comment by kg4vdk** [comment]
Oh no! All my best wishes to your wife for a speedy recovery.

> But I get the following message:

I don't see any included error message. Maybe a copy/paste went sideways.

When you can, please include that error message or a screenshot. If arcOS is booting, can you also include a screenshot of the arcOS partition layout using the "Disks" application, like this:

![Screenshot from 2024-11-29 20-09-42](https://github.com/user-attachments/assets/e9017933-054a-43b2-9433-e2b8012a33ca)

Mike

**Comment by ag5ym** [comment]
Hey Mike,
So tried to recreate the issue with the flash drive(s) and it worked fine. I guess you responding scared them so they are working.

The SD card I am trying to use in other system is still getting the issue. It is not as big a deal, but it would be nice if it would work. I am including the screen shot I got for you to see.
![IMG_9847](https://github.com/user-attachments/assets/30c70555-b229-4002-a768-3f5f35bd9899)

So at this time one of my laptops is working correctly but the small touchpad with only one USB port is still having the issue. If you have time you help would be great but I do not want to take any more than needed.

Thanks,

Travis

**Comment by ag5ym** [comment]
Here is the screen shot from the first email.
![IMG_9846](https://github.com/user-attachments/assets/dbf24b53-6782-495f-93b0-f33bf8934b84)

**Comment by kg4vdk** [comment]
I have an answer!!! When the persistent storage setup runs it ONLY looks for devices like `/dev/sdX`, and `/dev/nvmeX`. SD cards simply aren't being looked for. I'll work on adding SD cards (`/dev/mmcblkX`) to the persistent storage setup check. 

I'm working on a point release for "Hotel" currently, and I don't think this will take too much effort to implement. I think I even have a ThinkPad laying around that can boot from an SD card, so I'll be able to test it appropriately before release.

Thanks for bringing up the issue, and I'm glad the emailing scared away the gremlins regarding the USB drive :-)

Mike

**Comment by kg4vdk** [comment]
Persistent storage when using an SD card (/dev/mmcblkN) as the boot medium is fixed in the 21.3.0 "India" release.
